### ISSUE TITLE
༼ つ ◕_◕ ༽つ

### ISSUE THREAD

**Issue by ohmygod12121212** [Yue-Ra/ZombieAssist#1]
![af39b406548705caa7cf9aded9fbd742](https://cloud.githubusercontent.com/assets/8379858/18024901/45c1b47e-6c49-11e6-8222-d1e01f31aca7.jpg)

**Comment by Yue-Ra** [comment]
![qq 20160827114503](https://cloud.githubusercontent.com/assets/7745552/18024960/c721a144-6c4b-11e6-8be4-90440c51932a.jpg)
