### ISSUE TITLE
sourcemod hud api sucks

### ISSUE THREAD

**Issue by ohmygod12121212** [Yue-Ra/ZombieAssist#8]
sourcemod hud api sucks
params is stored globally and different huds confict with each other
try this instead
stock SendMsg_HudMsgAll(float x, float y,
                    int aRclr, int aGclr, int aBclr, int aTclr,
                    int bRclr, int bGclr, int bBclr, int bTclr,
                    int effect,
                    float fadein = 0.0, float fadeout = 0.0,
                    float holdtime, float fxtime = 0.0,
                    const char[] szMsg)
{
  Handle hBf = StartMessageAll("HudMsg");
  if (hBf != INVALID_HANDLE)
  {
     BfWriteByte(hBf, 0); //channel
     BfWriteFloat(hBf, x); // x ( -1 = center )
     BfWriteFloat(hBf, y); // y ( -1 = center )
     // second color
     BfWriteByte(hBf, aRclr); //r1
     BfWriteByte(hBf, aGclr); //g1
     BfWriteByte(hBf, aBclr); //b1
     BfWriteByte(hBf, aTclr); //a1 
     // init color
     BfWriteByte(hBf, bRclr); //r2
     BfWriteByte(hBf, bGclr); //g2
     BfWriteByte(hBf, bBclr); //b2
     BfWriteByte(hBf, bTclr); //a2
     BfWriteByte(hBf, effect); //effect (0 is fade in/fade out; 1 is flickery credits; 2 is write out)
     BfWriteFloat(hBf, fadein); //fadeinTime (message fade in time - per character in effect 2)
     BfWriteFloat(hBf, fadeout); //fadeoutTime
     BfWriteFloat(hBf, holdtime); //holdtime
     BfWriteFloat(hBf, fxtime); //fxtime (effect type(2) used)
     BfWriteString(hBf, szMsg); //Message
     EndMessage();
  }
}

**Comment by ohmygod12121212** [comment]
``stock SendMsg_HudMsgAll(float x, float y,
                    int aRclr, int aGclr, int aBclr, int aTclr,
                    int bRclr, int bGclr, int bBclr, int bTclr,
                    int effect,
                    float fadein = 0.0, float fadeout = 0.0,
                    float holdtime, float fxtime = 0.0,
                    const char[] szMsg)
{
  Handle hBf = StartMessageAll("HudMsg");
  if (hBf != INVALID_HANDLE)
  {
     BfWriteByte(hBf, 0); //channel
     BfWriteFloat(hBf, x); // x ( -1 = center )
     BfWriteFloat(hBf, y); // y ( -1 = center )
     // second color
     BfWriteByte(hBf, aRclr); //r1
     BfWriteByte(hBf, aGclr); //g1
     BfWriteByte(hBf, aBclr); //b1
     BfWriteByte(hBf, aTclr); //a1 // transparent?
     // init color
     BfWriteByte(hBf, bRclr); //r2
     BfWriteByte(hBf, bGclr); //g2
     BfWriteByte(hBf, bBclr); //b2
     BfWriteByte(hBf, bTclr); //a2
     BfWriteByte(hBf, effect); //effect (0 is fade in/fade out; 1 is flickery credits; 2 is write out)
     BfWriteFloat(hBf, fadein); //fadeinTime (message fade in time - per character in effect 2)
     BfWriteFloat(hBf, fadeout); //fadeoutTime
     BfWriteFloat(hBf, holdtime); //holdtime
     BfWriteFloat(hBf, fxtime); //fxtime (effect type(2) used)
     BfWriteString(hBf, szMsg); //Message
     EndMessage();
  }
}

**Comment by Yue-Ra** [comment]
经测试，不靠谱，单个还能用用，多个瞬间爆炸

**Comment by Yue-Ra** [comment]
参考

https://github.com/Yue-Ra/ZombieAssist/blob/master/zombie/function.inc#L106

如果不CloseHandle会内存泄露，创建个定时器干就行了
